### ISSUE TITLE
Add to F-Droid

### ISSUE THREAD

**Issue by pizzamaker** [anthony-salutari/DroidBay#1]
It would be handy to have this app distributed through F-Droid. Do you think that would be feasible?

**Comment by anthony-salutari** [comment]
Yes, this is a great idea and I hadn't thought of it before. After reading through the F-Droid rules, I believe my app qualifies for inclusion. I have approximately 15 issues to resolve and a bit of stability improvements/refactoring to do but I'm aiming for a stable release within the month.
